server:
  port: 8888
spring:
  application:
    name: confg-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shivajidas/capstone-project
          bootstrap: true


